platform:ios, '9.0'
inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'

target 'V2Client' do

pod 'AFNetworking', '~>3.1.0'
pod 'MBProgressHUD', '~>1.1.0'
pod 'MJExtension', '~>3.0.13'
pod 'MJRefresh', '~>3.1.15.7'
pod 'Masonry', '~>1.1.0'
end
